### ISSUE TITLE
"export 'default' (imported as 'compute') was not found in 'compute-scroll-into-view'

### ISSUE THREAD

**Issue by puhahalx** [scroll-into-view/scroll-into-view-if-needed#1139]
"scroll-into-view-if-needed":  "version": "2.2.31",
 "compute-scroll-into-view": "version": "1.0.20",

ERROR in ./node_modules/scroll-into-view-if-needed/es/index.js 44:47-54
"export 'default' (imported as 'compute') was not found in 'compute-scroll-into-view'

**Comment by stipsan** [comment]
This is fixed in `scroll-into-view-if-needed@3` and `compute-scroll-into-view@2`
