### ISSUE TITLE
compute.js

### ISSUE THREAD

**Issue by TTomasik** [scroll-into-view/scroll-into-view-if-needed#367]
Hi,
you left console.log in compute.js -> line 67 -> "console.log('test')"

**Comment by comatory** [comment]
Yes having the same problem here, kinda annoying since I send out my console logs into error tracking (so it takes up unnecessary space in console). Using v `1.5.1`.

**Comment by pavelloz** [comment]
I think this is ready to close, couldnt find this console log in current codebase :)
